language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw  
  - mysql -e 'CREATE DATABASE pontointeligente;'
services:
  - mysql    